# Generated by Django 4.2.8 on 2023-12-29 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Avaliação não pode ser inferior a 0 estrelas.'), django.core.validators.MaxValueValidator(5, 'Avaliação não pode ser superior a 5 estrelas.')])),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='movies.movie')),
            ],
        ),
    ]
