# Generated by Django 4.2.8 on 2023-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRA', 'Brasil'), ('CAN', 'Canadá'), ('GBR', 'Reino Unido'), ('FRA', 'França'), ('GER', 'Alemanha'), ('ITA', 'Itália'), ('JPN', 'Japão'), ('CHN', 'China'), ('IND', 'Índia'), ('AUS', 'Austrália'), ('RUS', 'Rússia'), ('ESP', 'Espanha'), ('MEX', 'México'), ('ARG', 'Argentina'), ('ZAF', 'África do Sul'), ('NGA', 'Nigéria'), ('KEN', 'Quênia'), ('SAU', 'Arábia Saudita'), ('KOR', 'Coreia do Sul'), ('IDN', 'Indonésia'), ('TUR', 'Turquia'), ('SWE', 'Suécia'), ('NOR', 'Noruega'), ('NLD', 'Países Baixos'), ('BEL', 'Bélgica'), ('AUT', 'Áustria'), ('NZL', 'Nova Zelândia'), ('SUI', 'Suíça'), ('POR', 'Portugal'), ('POL', 'Polônia'), ('IRN', 'Irã'), ('IRQ', 'Iraque'), ('SYR', 'Síria'), ('EGY', 'Egito')], max_length=100, null=True)),
            ],
        ),
    ]
